export default {
  question : [
    {
      tit:"asdasdadad",
      list:[{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      }]
    },
    {
      tit:"asdasdadad",
      list:[{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      }]
    },
    {
      tit:"asdasdadad",
      list:[{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      }]
    },
    {
      tit:"asdasdadad",
      list:[{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      }]
    },
    {
      tit:"asdasdadad",
      list:[{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      },{
        className:'sea',
        mian:''
      }]
    }
  ]
};
